project:
  render:
    - '*.qmd'
  type: website
  output-dir: _site

website:
  title: "Yi Huang"
  site-url: "https://yihuang314.github.io"
  description: "Academic homepage of Yi Huang"
  favicon: work_fig/NE_cover_2025.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
#     - href: team.qmd
#       text: Team
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: PI
      - href: hiring.qmd
        text: Opportunities
#      - href: fun.qmd
#        text: Fun
    right:
      - href: index.qmd
        text: EN
      - href: index.zh.qmd
        text: 中文

  page-footer:
    center: "2026 @ Yi Huang"

lang: en

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
    toc: false
    link-external-newwindow: true
    include-after-body: lang-switch.html
execute:
  freeze: auto




