---
title: "招生机会"
lang: zh
---

::: {.home-page}

## 博士生招生

我们正在招收多名博士生，计划于 2026 年秋季或 2027 年春季加入课题组。我们的研究旨在开发用于下一代人工智能的高能效智能计算系统，探索软硬件协同设计，重点关注两个互补方向：

- 基于 CMOS 和新型存储器件的脑启发电路与架构
- 基于模拟存内计算硬件的高能效算法与应用

### 为什么加入我们的团队？

#### 协作式指导与科研发展

课题组强调高参与度的科研指导，同时鼓励学生自由探索有挑战性的研究方向。团队成员将受益于覆盖硬件与软件的综合经验，并有机会在重要工程领域期刊（如 IEEE Transactions）以及高影响力跨学科期刊（如 Nature 系列）发表成果。欢迎联系[合作者](http://nano.ecs.umass.edu/?_ga=2.62088623.2061699384.1566844657-1135324780.1544805653)，了解与我们合作的实际体验。

#### 跨学科与协作环境

我们的 EECS 系涵盖电子工程、计算机工程和计算机科学方向，为从硬件到软件全栈的合作提供机会。系内还拥有神经形态架构、学习与应用方向的领先研究团队（[TENN Lab](https://neuromorphic.eecs.utk.edu/)），为跨学科研究提供了天然基础。此外，学校临近 [Oak Ridge National Laboratory](https://www.ornl.gov/)，为与世界一流研究机构合作提供机会。

#### 实验室之外的生活

科研是一场马拉松，而不是短跑；我们重视科研与生活的平衡。大烟山国家公园近在咫尺，适合课题组徒步、露营和户外活动。健身与健康也是课题组文化的一部分，PI 具备 ACE 认证私人教练和运动营养专家资质，可为感兴趣的同学提供相关建议。

### 我们期待的学生：

我们欢迎积极主动、热爱探索前沿方向的学生。理想候选人通常具备：

- 对面向下一代人工智能的脑启发电路、架构与算法有兴趣
- 扎实的模拟电路设计或机器学习算法基础
- 具有神经形态计算或存内计算相关经验者优先

### 如何申请：

有意加入团队的同学欢迎发送邮件至 yihuang@utk.edu，并附上以下材料：1) CV，2) 成绩单，3) 一份简短的研究兴趣与职业目标说明，4) TOEFL 或 IELTS 成绩（如适用）。

:::
